# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapsHelper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GoogleMapsHelper
pod 'SVHTTPRequest', '~> 0.5'
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
end
